name: mock_api
description: A simple mock API server for local development
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  shelf_static: ^1.1.0
  path: ^1.8.3
  http_parser: ^4.0.2
  shelf_cors_headers: ^0.1.5