site_name: Flutter Clean Starter
site_description: A production-ready Flutter starter template using Clean Architecture
site_author: Biruk Mekonnen
site_url: https://BrockMekonnen.github.io/flutter_clean_starter/
repo_url: https://github.com/BrockMekonnen/flutter_clean_starter
repo_name: BrockMekonnen/flutter_clean_starter
docs_dir: docs

theme:
  name: material
  language: en
  favicon: img/favicon.ico
  
  features:
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - content.code.copy
    - content.action.edit
    - search.highlight
    - search.suggest
    - toc.integrate
    - header.autohide
  palette:
    - scheme: default
      primary: blue
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    logo: material/rocket-launch
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Architecture: architecture.md
  - Folder Structure: folder_structure.md
  - Core:
      - Overview: _core/overview.md
      - Bootstrap: _core/bootstrap.md
      - Init Modules: _core/init_modules.md
      - Router: _core/app_router.md
      - Dependency Injection: _core/di.md
      - HTTP Client: _core/http_client.md
      - Database: _core/database.md
      - Theme: _core/theme.md
  - Modules:
      - Overview: modules/overview.md
      - Shared Module: modules/shared.md
      - Auth Module: modules/auth.md
      # - Post Module: modules/post.md
  - Contributing: contributing.md